### ISSUE TITLE
https://github.com/undoZen

### ISSUE THREAD

**Issue by vitrum** [jsconfcn/hangjs#2]
http://xueqiu.com/ is a well-known web site who using nodejs.

**Comment by JacksonTian** [comment]
他已经不在雪球了。雪球已经社区分享过多次，可能不会直接邀请为嘉宾，但沟通的机会肯定有。

**Comment by goddyZhao** [comment]
那先关闭这个issue了，下次我们可以在社区提供沟通机会。多谢推荐！
