### ISSUE TITLE
Cheng Zhao @zcbenz

### ISSUE THREAD

**Issue by fengmk2** [jsconfcn/hangjs#26]
## Cheng Zhao
- github: https://github.com/zcbenz
- topic: About atom and atom shell
- weibo: http://weibo.com/bigbigfool @笨小猫猫

He's our 沪JS speaker too, talking about node-webkit.

**Comment by fengmk2** [comment]
Confirmed he will show out on Hangjs.

**Comment by fengmk2** [comment]
@zcbenz ping

**Comment by zcbenz** [comment]
Sure, thanks!

**Comment by dead-horse** [comment]
:+1:

**Comment by goddyZhao** [comment]
Old Friend ：） @zcbenz

**Comment by goddyZhao** [comment]
@zcbenz 邀请函已发到你Github上填写的邮件地址，请尽快回复！
