### ISSUE TITLE
@鬼道: Ali Hybrid Api

### ISSUE THREAD

**Issue by fengmk2** [jsconfcn/hangjs#31]
# Ali Hybrid Api

分享着: 徐凯 (阿里花名: 鬼道), github: @luics
## 目标
1. 提供一套能够运行在独立浏览器和客户端的 API。
2. 对用户而言写一份代码可运行在：Android设备、iPhone、iPad 的客户端和独立浏览器。
## 架构
1. 用户环境：独立浏览器、Webview。
2. Ali Hybrid API（AHA）：按照 W3C 规范封装 Native 提供的接口。
3. Bridge：Native 与 Web 双向通信机制。
   - motion（加速度）等连续性事件需要考虑回调性能问题，避免频繁触发 Bridge。
4. 客户端：AHA 的数据提供方。
   - Native 最大程度兼容 W3C 相关规范，允许合理的扩展。

![1](http://i01.lw.aliimg.com/tfs/T1x3DLFBpbXXaReMkdLAIWANGqgz9x_0b674550_683_532.jpg)
## 参考

pg-api: http://docs.phonegap.com/en/3.3.0/#API%20Reference
ti-api: http://docs.appcelerator.com/titanium/3.0/#!/api
w3c: http://mobilehtml5.org/
dap: http://www.w3.org/2009/dap/
geo: http://www.w3.org/2008/geolocation/
motion: http://dev.w3.org/geo/api/spec-source-orientation.html
h5: http://www.w3.org/TR/2013/WD-html51-20131029/

**Comment by fengmk2** [comment]
详细请@luics 自行补充 :)

**Comment by goddyZhao** [comment]
@luics 邀请函已发到你github上填写的邮箱地址，请尽快回复！
