### ISSUE TITLE
@Sofish

### ISSUE THREAD

**Issue by liyinkan** [jsconfcn/hangjs#35]
https://github.com/sofish
男神……

**Comment by fengmk2** [comment]
@sofish 要来杭州分享分享么?

**Comment by afc163** [comment]
快，来杭州卖手机！

**Comment by sofish** [comment]
要是有女粉丝想听我分享才会来，顺跑卖手机 @fengmk2 @afc163

**Comment by fengmk2** [comment]
@sofish 必须有! 嘉宾有10分钟QA, 能卖很多广告.

**Comment by JacksonTian** [comment]
要不赞助点吧。

在 2014年4月4日，下午3:31，小鱼 notifications@github.com 写道：

**Comment by fakefish** [comment]
@sofish 现场抽奖送手机！

**Comment by sofish** [comment]
连个妹子都没有，赞助和抽奖都是浮云，只有提供广告的是好人

**Comment by Hsinglin** [comment]
@sofish 男神你从了吧！！

**Comment by fengmk2** [comment]
确认了

**Comment by sofish** [comment]
哈哈，争取到时候能讲点真正有用的东西

**Comment by goddyZhao** [comment]
@sofish 邀请函已发到你icloud邮箱，请尽快回复！

**Comment by yyclaw** [comment]
论 Node.js 在手机营销中的重要性
