### ISSUE TITLE
@dead_horse

### ISSUE THREAD

**Issue by fengmk2** [jsconfcn/hangjs#40]
@dead-horse

100% 的nodejs开发者

**Comment by fengmk2** [comment]
https://github.com/dead-horse

**Comment by dead-horse** [comment]
别黑，好歹还会点前端
不过好像真没什么可以讲的东西啊

**Comment by fengmk2** [comment]
哈哈，只能说你接触的都好超前
2014-4-6 下午12:44于 "dead_horse" notifications@github.com写道：
