### ISSUE TITLE
@郭宇

### ISSUE THREAD

**Issue by fengmk2** [jsconfcn/hangjs#43]
@turingou
github: https://github.com/turingou
topic: 开源项目的管理和维护

[douban.fm](https://github.com/turingou/douban.fm) 命令行版的作者, 开发和维护了大量开源模块.
微博: [@郭宇](http://weibo.com/137601206)

**Comment by goddyZhao** [comment]
@turingou 邀请函已经发送到你Github填写的邮箱地址，请尽快回复！

**Comment by guo-yu** [comment]
@goddyZhao 好的，已回复了邮件。

**Comment by fengmk2** [comment]
presentation https://github.com/turingou/hangjs
