### ISSUE TITLE
@常胤 中途岛

### ISSUE THREAD

**Issue by fengmk2** [jsconfcn/hangjs#44]
[也谈基于NodeJS的全栈式开发（基于NodeJS的前后端分离）](http://ued.taobao.org/blog/2014/04/full-stack-development-with-nodejs/)

**Comment by fengmk2** [comment]
分享着来自 淘宝UED 小马团队.

**Comment by JacksonTian** [comment]
+1

发自我的 iPhone

**Comment by satans17** [comment]
我们会尽快确定主题！

**Comment by cycyewt** [comment]
我顶

**Comment by goddyZhao** [comment]
@satans17 邀请函已发，请尽快回复！
